export default [
  {
    name: "YouTube",
    abbr: "Yt",
    type: "core",
    url: "https://www.youtube.com/",
  },
  { name: "Twitch", abbr: "Tw", type: "core", url: "https://www.twitch.tv/" },
  { name: "Notion", abbr: "No", type: "core", url: "https://www.notion.so" },
  {
    name: "Color Palatte Generator",
    abbr: "Cp",
    type: "tool",
    url: "https://www.coolors.co/generate",
  },
  {
    name: "Color Contrast Checker",
    abbr: "Cc",
    type: "tool",
    url: "https://colorable.jxnblk.com/",
  },
  {
    name: "Flexbox Guide",
    abbr: "Fb",
    type: "reference",
    url: "https://www.css-tricks.com/snippets/css/a-guide-to-flexbox/",
  },
  {
    name: "Grid Guide",
    abbr: "Gr",
    type: "reference",
    url: "https://www.css-tricks.com/snippets/css/complete-guide-grid/",
  },
  {
    name: "Markdown Cheatsheet",
    abbr: "Md",
    type: "reference",
    url: "https://www.github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet",
  },
  {
    name: "FreeCodeCamp",
    abbr: "Fc",
    type: "learn",
    url: "https://www.freecodecamp.org/learn",
  },
  {
    name: "Advent of Code",
    abbr: "Ac",
    type: "learn",
    url: "https://www.adventofcode.com/",
  },
  { name: "RegExr", abbr: "Re", type: "tool", url: "https://www.regexr.com/" },
  {
    name: "A11y Checklist",
    abbr: "Al",
    type: "reference",
    url: "https://www.a11yproject.com/checklist/",
  },
  {
    name: "Vue Docs",
    abbr: "Vu",
    type: "reference",
    url: "https://www.vuejs.org/guide/quick-start.html",
  },
  {
    name: "React Docs",
    abbr: "Re",
    type: "reference",
    url: "https://react.dev/reference/react",
  },
  {
    name: "Angular Docs",
    abbr: "Ng",
    type: "reference",
    url: "https://www.angular.io/docs",
  },
  {
    name: "TypeScript Docs",
    abbr: "Ts",
    type: "reference",
    url: "https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html",
  },
  {
    name: "Joy of React",
    abbr: "Jr",
    type: "learn",
    url: "https://courses.joshwcomeau.com/joy-of-react",
  },
  {
    name: "Box-shadow Generator",
    abbr: "Bs",
    type: "tool",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Box-shadow_generator",
  },
  {
    name: "Astro Docs",
    abbr: "As",
    type: "reference",
    url: "https://docs.astro.build/en/install/auto/",
  },
  {
    name: "Science of Well-Being",
    abbr: "Wb",
    type: "learn",
    url: "https://www.coursera.org/learn/the-science-of-well-being/home",
  },
  {
    name: "Todoist",
    abbr: "Td",
    type: "core",
    url: "https://todoist.com/app/",
  },
];
